name: Deploy Storybook on post-merge

on:
  push:
    branches:
      - development/*
jobs:
  publish-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10.x
      - run: npm install
      - run: npm run storybook:deploy --ci --host-token-env-variable=GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.core_ui_github_token}}
